/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M10
 * Generated at: 2018-09-13 11:51:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.settings.dictionary.type;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class save_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.scheme}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(':');
      out.write('/');
      out.write('/');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.serverName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(':');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.serverPort}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"jquery/bootstrap_3.3.0/css/bootstrap.min.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"jquery/bootstrap-datetimepicker-master/css/bootstrap-datetimepicker.min.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"jquery/jquery-1.11.1-min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"jquery/bootstrap_3.3.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.error {\r\n");
      out.write("\t\tcolor:red;\r\n");
      out.write("\t\tfont-size:12px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t//页面加载完毕后给id=\"code\"的文本框绑定失去焦点事件\r\n");
      out.write("\t\t$(\"#code\").blur(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar code = $.trim(this.value);//取得编码位置输入的值\r\n");
      out.write("\t\t\t//alert(code);\r\n");
      out.write("\t\t\tif(code==\"\"){\r\n");
      out.write("\t\t\t\t//提示错误信息\r\n");
      out.write("\t\t\t\t$(\"#codeErrorMsg\").text(\"字型编码不能为空\");\r\n");
      out.write("\t\t\t}else {\r\n");
      out.write("\t\t\t\t//不为空,继续判断是否含有特殊符号\r\n");
      out.write("\t\t\t\t/*\r\n");
      out.write("\t\t\t\t\tJS的两种创建正则表达式对象的方式:\r\n");
      out.write("\t\t\t\t\t\tvar regExp = new RegExp(\"正则表达式\") //JS内置对象RegExp\r\n");
      out.write("\t\t\t\t\t\tvar regExp = /正则表达式/  //常用\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t常见政策表达式符号:\r\n");
      out.write("\t\t\t\t\t\t\\s 表示空白\r\n");
      out.write("\t\t\t\t\t\t[0-9]表示0-9任意一个数字\r\n");
      out.write("\t\t\t\t\t\t[0-9]{2} 表示0-9任意两个数字\r\n");
      out.write("\t\t\t\t\t\t[0-9]{2,} 表示0-9至少两个数字\r\n");
      out.write("\t\t\t\t\t\t[0-9]{2,4} 表示0-9数字出现次数为：[2到4次]\r\n");
      out.write("\t\t\t\t\t\t[0-9]* 表示0-9数字出现次数为：0--N次\r\n");
      out.write("\t\t\t\t\t\t[0-9]+ 表示0-9数字出现次数为：1--N次\r\n");
      out.write("\t\t\t\t\t\t[0-9]? 表示0-9数字出现次数为：0或1次\r\n");
      out.write("\t\t\t\t\t\t[a-zA-Z0-9]{3} \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t^ 表示字符串开始\r\n");
      out.write("\t\t\t\t\t\t$ 表示字符串结束\r\n");
      out.write("\t\t\t\t*/\r\n");
      out.write("\t\t\t\tvar regExp = /^[a-zA-Z0-9]+$/\r\n");
      out.write("\t\t\t\t// 正则表达式对象有test()方法，专门用来测试字符串和正则表达式是否可以正常匹配\r\n");
      out.write("\t\t\t\tvar ok = regExp.test(code);\r\n");
      out.write("\t\t\t\tif(ok){\r\n");
      out.write("\t\t\t\t\t// 不为空，并且不含有特殊符号，继续判断它的唯一性：这个需要发送ajax请求\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\t\t\turl : \"settings/dictionary/type/checkCodeUnique.do\",\r\n");
      out.write("\t\t\t\t\t\tcache : false, //自动添加时间戳,解决浏览器对于get方法的缓存问题\r\n");
      out.write("\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\"code\" : code\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tsuccess: function(json){\r\n");
      out.write("\t\t\t\t\t\t\t//{\"success\" : true} 表示可以使用\r\n");
      out.write("\t\t\t\t\t\t\t//{\"success\" : false} 表示不能使用(已存在)\r\n");
      out.write("\t\t\t\t\t\t\tif(json.success){\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#codeErrorMsg\").text(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#codeErrorMsg\").text(\"字典类型编码已存在!\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}else {\r\n");
      out.write("\t\t\t\t\t$(\"#codeErrorMsg\").text(\"字典类型编码只能由数字和字母组成!\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//绑定获取焦点事件\r\n");
      out.write("\t\t$(\"#code\").focus(function(){\r\n");
      out.write("\t\t\tif($(\"#codeErrorMsg\").text() != \"\"){\r\n");
      out.write("\t\t\t\t$(\"#code\").val(\"\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$(\"#codeErrorMsg\").text(\"\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#saveBtn\").click(function(){\r\n");
      out.write("\t\t\t// 手动触发blur事件\r\n");
      out.write("\t\t\t$(\"#code\").blur(); //blur事件一旦发生之后，就会发送ajax，这个ajax设置为同步之后，浏览器被锁住。直到该ajax请求结束，这里代码才能继续往下执行。\r\n");
      out.write("\t\t\tif($(\"#codeErrorMsg\").text() == \"\"){\r\n");
      out.write("\t\t\t\t$(\"#dicTypeForm\").submit();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div style=\"position:  relative; left: 30px;\">\r\n");
      out.write("\t\t<h3>新增字典类型</h3>\r\n");
      out.write("\t  \t<div style=\"position: relative; top: -40px; left: 70%;\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"saveBtn\">保存</button>\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-default\" onclick=\"window.history.back();\">取消</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<hr style=\"position: relative; top: -40px;\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<form id=\"dicTypeForm\" action=\"settings/dictionary/type/save.do\" method=post class=\"form-horizontal\" role=\"form\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"create-code\" class=\"col-sm-2 control-label\">编码<span style=\"font-size: 15px; color: red;\">*</span></label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\" style=\"width: 300px;\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"code\" name=\"code\" style=\"width: 200%;\" placeholder=\"编码作为主键，不能是中文\">\r\n");
      out.write("\t\t\t\t<span id=\"codeErrorMsg\" class=\"error\"></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"create-name\" class=\"col-sm-2 control-label\">名称</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\" style=\"width: 300px;\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"name\" name=\"name\" style=\"width: 200%;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"create-describe\" class=\"col-sm-2 control-label\">描述</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\" style=\"width: 300px;\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" rows=\"3\" id=\"description\" name=\"description\" style=\"width: 200%;\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t<div style=\"height: 200px;\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
